name: Package

on: [push, pull_request]

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install poetry
      run: pipx install poetry
    - name: Print Python version
      run: python -c "import struct, sys; print('{}\n{} bits'.format(sys.version, struct.calcsize('P') * 8))"
    - name: Install dependencies
      run: poetry install
    - name: Run PyInstaller
      run: poetry run pyinstaller package/cli.spec
    - uses: actions/upload-artifact@v1
      with:
        name: cli-${{ matrix.os }}
        path: dist/SerialPcControl
