name: Tests

on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.3
    - name: Print Python version
      run: python -c "import struct, sys; print('{}\n{} bits'.format(sys.version, struct.calcsize('P') * 8))"
    - name: Install dependencies
      run: poetry install
    - name: Run pytest
      run: poetry run python -m pytest
    - name: Run mypy
      run: poetry run python -m mypy .
    - name: Run Flake8
      run: poetry run python -m flake8
    - name: Run black
      run: poetry run python -m black . --check --diff
